/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  productType: 'poster' | 'kort' | 'bricka' | 'skarbrada' | 'underlagg' | 'original' | 'ovrigt'
  price: number
  size?: string
  material?: string
  description?: string
  collection?: string
  stripePaymentLink?: string
  soldOut?: boolean
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  category: 'barnbocker' | 'kartor' | 'tidskrifter' | 'reklam' | 'konst'
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  featured?: boolean
  year?: string
  client?: string
  author?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  exhibitions?: Array<{
    year: string
    title: string
    venue?: string
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroText?: string
  footerText?: string
  contactInfo?: {
    address?: string
    phone?: string
    email?: string
    swish?: string
  }
  socialMedia?: {
    instagram?: string
    facebook?: string
  }
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | AboutPage
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0] {    ...,    "heroImageUrl": heroImage.asset->url  }
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroText?: string
  footerText?: string
  contactInfo?: {
    address?: string
    phone?: string
    email?: string
    swish?: string
  }
  socialMedia?: {
    instagram?: string
    facebook?: string
  }
  title?: string
  description?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  heroImageUrl: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(title asc) {    _id,    title,    slug,    category,    year,    client,    "coverImageUrl": coverImage.asset->url,    featured  }
export type AllProjectsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  category: 'barnbocker' | 'kartor' | 'konst' | 'reklam' | 'tidskrifter'
  year: string | null
  client: string | null
  coverImageUrl: string | null
  featured: boolean | null
}>

// Source: sanity/lib/queries.ts
// Variable: featuredProjectsQuery
// Query: *[_type == "project" && featured == true] | order(title asc) {    _id,    title,    slug,    category,    "coverImageUrl": coverImage.asset->url  }
export type FeaturedProjectsQueryResult = Array<{
  _id: string
  title: string
  slug: Slug
  category: 'barnbocker' | 'kartor' | 'konst' | 'reklam' | 'tidskrifter'
  coverImageUrl: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    category,    year,    client,    author,    coverImage,    "coverImageUrl": coverImage.asset->url,    images[] {      _key,      alt,      asset-> { _id, url, metadata { dimensions } }    },    description,    featured  }
export type ProjectQueryResult = {
  _id: string
  title: string
  slug: Slug
  category: 'barnbocker' | 'kartor' | 'konst' | 'reklam' | 'tidskrifter'
  year: string | null
  client: string | null
  author: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  coverImageUrl: string | null
  images: Array<{
    _key: string
    alt: null
    asset: {
      _id: string
      url: string
      metadata: {
        dimensions: SanityImageDimensions | null
      } | null
    } | null
  }> | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  featured: boolean | null
} | null

// Source: sanity/lib/queries.ts
// Variable: projectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)] {    "slug": slug.current  }
export type ProjectSlugsQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: productsQuery
// Query: *[_type == "product"] | order(coalesce(orderRank, "~") asc, title asc) {    _id,    title,    productType,    price,    size,    material,    "imageUrl": image.asset->url,    description,    stripePaymentLink,    soldOut,    collection  }
export type ProductsQueryResult = Array<{
  _id: string
  title: string
  productType: 'bricka' | 'kort' | 'original' | 'ovrigt' | 'poster' | 'skarbrada' | 'underlagg'
  price: number
  size: string | null
  material: string | null
  imageUrl: string | null
  description: string | null
  stripePaymentLink: string | null
  soldOut: boolean | null
  collection: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0] {    _id,    title,    portrait,    "portraitUrl": portrait.asset->url,    bio,    exhibitions  }
export type AboutPageQueryResult = {
  _id: string
  title: string | null
  portrait: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  portraitUrl: string | null
  bio: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  exhibitions: Array<{
    year: string
    title: string
    venue?: string
    _key: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        link {          ...,          _type == "link" => {            ...,            "page": page->slug.current,            "post": post->slug.current          }        }      },      _type == "infoSection" => {        ...      },    }  }
export type GetPageQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current  }
export type PagesSlugsResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(date desc) {    _id,    title,    "slug": slug.current,    excerpt,    date,    "author": author->{      firstName,      lastName,      picture    }  }
export type AllPostsQueryResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    date,    content,    coverImage,    "author": author->{      firstName,      lastName,      picture    }  }
export type PostQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]{    "slug": slug.current  }
export type PostPagesSlugsResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type in ["page", "post", "project"] && defined(slug.current)]{    _type,    "slug": slug.current,    _updatedAt  }
export type SitemapDataResult = Array<{
  _type: 'project'
  slug: string
  _updatedAt: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "settings"][0] {\n    ...,\n    "heroImageUrl": heroImage.asset->url\n  }\n': SettingsQueryResult
    '\n  *[_type == "project"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    category,\n    year,\n    client,\n    "coverImageUrl": coverImage.asset->url,\n    featured\n  }\n': AllProjectsQueryResult
    '\n  *[_type == "project" && featured == true] | order(title asc) {\n    _id,\n    title,\n    slug,\n    category,\n    "coverImageUrl": coverImage.asset->url\n  }\n': FeaturedProjectsQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    category,\n    year,\n    client,\n    author,\n    coverImage,\n    "coverImageUrl": coverImage.asset->url,\n    images[] {\n      _key,\n      alt,\n      asset-> { _id, url, metadata { dimensions } }\n    },\n    description,\n    featured\n  }\n': ProjectQueryResult
    '\n  *[_type == "project" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ProjectSlugsQueryResult
    '\n  *[_type == "product"] | order(coalesce(orderRank, "~") asc, title asc) {\n    _id,\n    title,\n    productType,\n    price,\n    size,\n    material,\n    "imageUrl": image.asset->url,\n    description,\n    stripePaymentLink,\n    soldOut,\n    collection\n  }\n': ProductsQueryResult
    '\n  *[_type == "aboutPage"][0] {\n    _id,\n    title,\n    portrait,\n    "portraitUrl": portrait.asset->url,\n    bio,\n    exhibitions\n  }\n': AboutPageQueryResult
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        link {\n          ...,\n          _type == "link" => {\n            ...,\n            "page": page->slug.current,\n            "post": post->slug.current\n          }\n        }\n      },\n      _type == "infoSection" => {\n        ...\n      },\n    }\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': PagesSlugsResult
    '\n  *[_type == "post"] | order(date desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    date,\n    "author": author->{\n      firstName,\n      lastName,\n      picture\n    }\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    date,\n    content,\n    coverImage,\n    "author": author->{\n      firstName,\n      lastName,\n      picture\n    }\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': PostPagesSlugsResult
    '\n  *[_type in ["page", "post", "project"] && defined(slug.current)]{\n    _type,\n    "slug": slug.current,\n    _updatedAt\n  }\n': SitemapDataResult
  }
}
